name: Test
concurrency: production

runs:
  using: "composite"
  steps:
    - id: branch-name
      uses: tj-actions/branch-names@v7

    - name: Grep and Purge all camo github user content images
      shell: bash
      run: |
        urls=$(curl -sLk https://github.com/${{github.repository_owner}}/${{ github.event.repository.name }}/tree/${{ steps.branch-name.outputs.current_branch }}|grep -Eo "(http|https)://camo.githubusercontent.com[a-zA-Z0-9./?=_%:-]*")

        while IFS= read -r line; do curl -X PURGE $line ; done <<< $urls

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm' # Cache npm dependencies

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Display test results
        if: failure() # This step runs only if the tests fail
        run: cat ./test-results.txt || echo "No test results file found"
