name: Combined Tests

on:
  push:
    branches: [ develop, release ]
  pull_request:
    branches: [ develop, release ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run unit tests with Jest
      - name: Run unit tests
        run: npm run test:unit

      # Run end-to-end tests with Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run end-to-end tests
        run: npm run test:e2e

      # Upload Playwright report
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Display test results in case of failure
      - name: Display Jest test results
        if: failure()
        run: cat ./coverage/lcov-report/index.html || echo "No coverage report found"

      - name: Display Playwright report link
        if: success() || failure()
        run: |
          echo "Playwright report available in the uploaded artifact."
